language: go
services:
  - docker
cache:
  directories:
    - ~/docker
go:
  - 1.9.2
before_install:
  - go get github.com/docker/docker/api/types
  - go get github.com/docker/docker/client
  - go get github.com/gorilla/mux
script:
  - make
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push swarmpit/agent
