language: go
services:
  - docker
cache:
  directories:
    - ~/docker
go:
 - 1.9.2
before_install:
  - go get https://github.com/docker/docker/api/types
  - go get https://github.com/docker/docker/client
script:
  - make
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push swarmpit/swarmpit-ec;
    fi