language: go
services:
  - docker
cache:
  directories:
    - ~/docker
script:
  - make
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push swarmpit/swarmpit-ec;
    fi